In [6]:
import torch

lista = [
    [1, 2, 3],
    [4, 5, 6]
]
tensorlegal = torch.FloatTensor(lista)
print(tensorlegal.dtype)

tentorlegal = torch.LongTensor(lista)
print(tensorlegal.dtype)



torch.float32
torch.float32


In [7]:
import numpy as np

arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)
print(tns)
print(tns.dtype)


[[0.0408275  0.33400142 0.70225866 0.46041854]
 [0.7373369  0.16529727 0.14043875 0.04368587]
 [0.55520517 0.24539276 0.15398601 0.55584234]]
float64
tensor([[0.0408, 0.3340, 0.7023, 0.4604],
        [0.7373, 0.1653, 0.1404, 0.0437],
        [0.5552, 0.2454, 0.1540, 0.5558]], dtype=torch.float64)
torch.float64


In [8]:
import torch
a = torch.zeros(4,4)
print(a)
print(type(a))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
<class 'torch.Tensor'>


In [9]:
tnsr = torch.rand(4,4)
print(tnsr)

tnsr[0, 2] = -10
print(tnsr)

print("PARTIDO", tns[:2])
print(tnsr.size())

tensor([[0.9343, 0.3418, 0.6170, 0.4889],
        [0.4652, 0.9873, 0.2158, 0.5699],
        [0.7511, 0.4779, 0.8548, 0.0964],
        [0.1760, 0.6520, 0.0076, 0.0610]])
tensor([[ 9.3431e-01,  3.4180e-01, -1.0000e+01,  4.8886e-01],
        [ 4.6523e-01,  9.8735e-01,  2.1581e-01,  5.6986e-01],
        [ 7.5108e-01,  4.7785e-01,  8.5477e-01,  9.6427e-02],
        [ 1.7600e-01,  6.5198e-01,  7.5909e-03,  6.1028e-02]])
PARTIDO tensor([[0.0408, 0.3340, 0.7023, 0.4604],
        [0.7373, 0.1653, 0.1404, 0.0437]], dtype=torch.float64)
torch.Size([4, 4])


In [11]:
import torch
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

print(device)

tns = tns.to(device)
print(tns)


cuda
tensor([[0.0408, 0.3340, 0.7023, 0.4604],
        [0.7373, 0.1653, 0.1404, 0.0437],
        [0.5552, 0.2454, 0.1540, 0.5558]], device='cuda:0',
       dtype=torch.float64)


In [13]:
import torch
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())
print('--------------------------------')
print(resultado)

torch.Size([5, 8])
--------------------------------
tensor([[-0.2447,  2.6154, -0.5404,  2.0108, -0.8893, -3.0667, -3.3739,  0.1672],
        [-3.8075,  1.7590,  2.7923, -0.2586, -2.7343, -1.3398, -3.8717, -0.1745],
        [ 1.7778,  1.0640, -1.1515,  1.5756,  1.1270, -0.9887, -1.5810,  0.0518],
        [ 0.0578,  1.6945, -1.9731,  1.5683, -0.4124, -2.7975, -0.5032,  0.5316],
        [ 1.2743,  0.4998, -2.3521,  1.0698, -0.6288, -2.2470,  1.9853,  0.3475]])


In [18]:
import torch
tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147, 1)

tns1 = tns1.view(-1, 1)
soma = tns1 + tns2

print(soma)
print("----------------------------------------")
print(tns1)

tensor([[-1.7242],
        [ 1.0423],
        [ 0.8463],
        [-3.0659],
        [ 0.3980],
        [-1.7738],
        [ 0.9146],
        [ 2.5705],
        [ 1.0401],
        [-1.0759],
        [ 0.0610],
        [ 1.3941],
        [ 0.9641],
        [ 0.6724],
        [-1.0982],
        [-0.3276],
        [-1.3465],
        [-0.7251],
        [-1.1500],
        [-1.6041],
        [-0.7080],
        [ 0.5330],
        [-0.3427],
        [-0.9843],
        [ 1.5050],
        [-2.8942],
        [-0.3856],
        [-0.4054],
        [-1.0816],
        [-1.6996],
        [ 0.6541],
        [ 1.6545],
        [-0.4828],
        [-1.3450],
        [ 5.4542],
        [-1.3788],
        [ 1.8244],
        [ 1.2739],
        [-2.8981],
        [ 0.8129],
        [-0.9680],
        [ 1.1577],
        [ 1.3731],
        [ 0.4191],
        [ 0.1418],
        [-0.1927],
        [ 1.4156],
        [ 0.3977],
        [-0.5429],
        [ 1.4756],
        [ 0.6594],
        [ 1.0731],
        [-0.